---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: checkpoint
namespace: checkpoint
readme: README.md
repository: https://github.com/ansible-collections/checkpoint
